"use strict";
// import {
//     theChosenProduct
// } from "./script.js";

const allItems = [
    {
        id : 1,
        name : "playstation 5",
        info : "The PlayStation 5 (PS5) is a home video game console developed by Sony Interactive Entertainment.",
        quantity : 10,
        price : 250,
        image : "/pics/img-1.jpg",
    },
    {
        id : 2,
        name : "smart watch",
        info : "A smartwatch is a wearable computer in the form of a watch;",
        quantity : 5,
        price : 150,
        image : "/pics/img-2.jpg",
    },
    {
        id : 3,
        name : "labtop",
        info : "A laptop computer or notebook computer, also known as a laptop or notebook",
        quantity : 12,
        price : 230,
        image : "/pics/img-3.jpg",
    },
    {
        id : 4,
        name : "computer case",
        info : "A computer case safeguards all of the important—and expensive—parts of a PC or other computing device.",
        quantity : 7,
        price : 550,
        image : "/pics/img-4.jpg",
    },
    {
        id : 5,
        name : "alexa",
        info : "A. Alexa is Amazon's voice AI. Alexa lives in the cloud and is happy to help",
        quantity : 3,
        price : 100,
        image : "/pics/img-5.jpg",
    },
    {
        id : 6,
        name : "printer",
        info : "A printer is a device that accepts text and graphic output from a computer and transfers the information to paper",
        quantity : 17,
        price : 70,
        image : "/pics/img-6.jpg",
    },
    {
        id : 7,
        name : "fax machine",
        info : "Fax machines scan a document, treating the text and images as a single fixed graphic image and converting it into a bitmap.",
        quantity : 4,
        price : 60,
        image : "/pics/img-7.jpg",
    },
    {
        id : 8,
        name : "mobile",
        info : "A mobile phone (cellphone, etc.) is a portable telephone that can make and receive calls over a radio frequency link while the user is moving",
        quantity : 32,
        price : 180,
        image : "/pics/img-8.jpg",
    },
    {
        id : 9,
        name : "digital clock",
        info : "A digital clock is a type of clock that displays the time digitally",
        quantity : 11,
        price : 30,
        image : "/pics/img-9.jpg",
    },
    {
        id : 10,
        name : "bower bank",
        info : "A Power Bank is a portable charger designed to recharge your electronic devices when you're on the move.",
        quantity : 50,
        price : 50,
        image : "/pics/img-10.jpg",
    },
    {
        id : 11,
        name : "coffee maker",
        info : "A coffee maker is described as a plug in appliance that pushes hot water through coffee beans to create coffee. ",
        quantity : 5,
        price : 180,
        image : "/pics/img-11.jpg",
    },
    {
        id : 12,
        name : "toaster",
        info : "A toaster is a small electric appliance that uses radiant heat to brown sliced bread into toast.",
        quantity : 3,
        price : 70,
        image : "/pics/img-12.jpg",
    },
    {
        id : 13,
        name : "microwave",
        info : "A microwave oven is an electric oven that heats and cooks food by exposing it to electromagnetic radiation in the microwave frequency range.",
        quantity : 10,
        price : 100,
        image : "/pics/img-13.jpg",
    },
    {
        id : 14,
        name : "TV",
        info : "Television (TV) is a telecommunication medium for transmitting moving images and sound",
        quantity : 15,
        price : 150,
        image : "/pics/img-14.jpg",
    },
    {
        id : 15,
        name : "iron",
        info : "A clothes iron is a small appliance that, when heated, is used to press clothes to remove wrinkles and unwanted creases.",
        quantity : 1,
        price : 100,
        image : "/pics/img-15.jpg",
    },
    {
        id : 16,
        name : "AC",
        info : "An air conditioner cools your home with a cold indoor coil called the evaporator.",
        quantity : 6,
        price : 180,
        image : "/pics/img-16.jpg",
    },
    {
        id : 17,
        name : "radio",
        info : "Radio is the technology of signaling and communicating using radio waves.",
        quantity : 12,
        price : 75,
        image : "/pics/img-17.jpg",
    },
    {
        id : 18,
        name : "tablet",
        info : "A tablet is a wireless, portable personal computer with a touchscreen interface. ",
        quantity : 2,
        price : 105,
        image : "/pics/img-18.jpg",
    },
    {
        id : 19,
        name : "fan",
        info : "A fan is a powered machine used to create a flow of air",
        quantity : 17,
        price : 25,
        image : "/pics/img-19.jpg",
    },
    {
        id : 20,
        name : "DVD",
        info : "The DVD is a digital optical disc data storage format.",
        quantity : 10,
        price : 90,
        image : "/pics/img-20.jpg",
    },
    {
        id : 21,
        name : "camera",
        info : "A camera is an optical instrument that captures images.",
        quantity : 9,
        price : 110,
        image : "/pics/img-21.jpg",
    },
    {
        id : 22,
        name : "flashlight",
        info : "A flashlight (US, CA) or torch (UK, AU) is a portable hand-held electric lamp.",
        quantity : 17,
        price : 50,
        image : "/pics/img-22.jpg",
    },
    {
        id : 23,
        name : "flash memory",
        info : "Flash memory, also known as flash storage, is a type of nonvolatile memory that erases data in units called blocks and rewrites data at the byte level",
        quantity : 19,
        price : 25,
        image : "/pics/img-23.jpg",
    },
    {
        id : 24,
        name : "hard drive",
        info : "A hard drive is the hardware component that stores all of your digital content. ",
        quantity : 0,
        price : 60,
        image : "/pics/img-24.jpg",
    },
    {
        id : 25,
        name : "monitor",
        info : "A monitor is an electronic output device that is also known as a video display terminal (VDT) or a video display unit (VDU).",
        quantity : 4,
        price : 200,
        image : "/pics/img-25.jpg",
    },
    {
        id : 26,
        name : "speakers",
        info : "The primary objective of speakers is to offer audio output for the listener",
        quantity : 8,
        price : 130,
        image : "/pics/img-26.jpg",
    },
    {
        id : 27,
        name : "projector",
        info : "A projector or image projector is an optical device that projects an image (or moving images)",
        quantity : 10,
        price : 250,
        image : "/pics/img-27.jpg",
    },
    {
        id : 28,
        name : "VR",
        info : "Virtual Reality (VR) is a computer-generated environment with scenes and objects that appear to be real",
        quantity : 0,
        price : 350,
        image : "/pics/img-28.jpg",
    },
    {
        id : 29,
        name : "receiver",
        info : "receiver, in electronics, any of various devices that accept signals, such as radio waves",
        quantity : 8,
        price : 70,
        image : "/pics/img-29.jpg",
    },
    {
        id : 30,
        name : "microphone",
        info : "A microphone, colloquially called mic or mike is a transducer that converts sound into an electrical signal.",
        quantity : 11,
        price : 90,
        image : "/pics/img-30.jpg",
    },
    {
        id : 31,
        name : "earbuds",
        info : "Earbuds are basically a pair of tiny speakers that you wear inside your ears.",
        quantity : 2,
        price : 115,
        image : "/pics/img-31.jpg",
    },
    {
        id : 32,
        name : "mixer",
        info : "Mixers help automate the repetitive tasks of stirring, whisking or beating",
        quantity : 9,
        price : 65,
        image : "/pics/img-32.jpg",
    },
    {
        id : 33,
        name : "hand blender",
        info : "hand blenders for chopping vegetables, making purees, soups and sauces",
        quantity : 13,
        price : 75,
        image : "/pics/img-33.jpg",
    },
    {
        id : 34,
        name : "video camera",
        info : "A video camera is an optical instrument that captures videos",
        quantity : 8,
        price : 100,
        image : "/pics/img-34.jpg",
    },
    {
        id : 35,
        name : "babyliss",
        info : "BaBylissPRO have been producing innovative electrical products to inspire the creativity of professional hairdressers, from session to salon and beyond.",
        quantity : 20,
        price : 40,
        image : "/pics/img-35.jpg",
    },
    {
        id : 36,
        name : "mouse",
        info : "A computer mouse (plural mice, also mouses) is a hand-held pointing device that detects two-dimensional motion relative to a surface",
        quantity : 7,
        price : 50,
        image : "/pics/img-36.jpg",
    },
    {
        id : 37,
        name : "keyboard",
        info : "A computer keyboard is a peripheral input device modeled after the typewriter keyboardwhich uses an arrangement of buttons or keys to act as mechanical",
        quantity : 10,
        price : 55,
        image : "/pics/img-37.jpg",
    },
    {
        id : 38,
        name : "RAM",
        info : "RAM (random access memory) is a computer's short-term memory, where the data that the processor is currently using is stored. ",
        quantity : 3,
        price : 125,
        image : "/pics/img-38.jpg",
    },
    {
        id : 39,
        name : "Nintendo",
        info : "Nintendo Switch is designed to fit your life, transforming from home console to portable system in a snap.",
        quantity : 9,
        price : 150,
        image : "/pics/img-39.jpg",
    },
    {
        id : 40,
        name : "Xbox",
        info : "Xbox is a video gaming brand created and owned by Microsoft.",
        quantity : 1,
        price : 200,
        image : "/pics/img-40.jpg",
    },
    {
        id : 41,
        name : "scanner",
        info : "A scanner is a device that captures images from photographic prints, posters",
        quantity : 14,
        price : 170,
        image : "/pics/img-41.jpg",
    },
    {
        id : 42,
        name : "security camera",
        info : "A home security camera is a video recording device that captures footage of your home and property that you can view on a smartphone, tablet,",
        quantity : 5,
        price : 150,
        image : "/pics/img-42.jpg",
    },
    {
        id : 43,
        name : "electronic grill",
        info : "A grilling unit that uses an electric element to supply a constant heat source.",
        quantity : 12,
        price : 190,
        image : "/pics/img-43.jpg",
    },
    {
        id : 44,
        name : "router",
        info : "A router is a device that connects two or more packet-switched networks or subnetworks",
        quantity : 10,
        price : 80,
        image : "/pics/img-44.jpg",
    },
    {
        id : 45,
        name : "usb charger",
        info : "A USB charger is a cable that's used to charge an electrical device",
        quantity : 19,
        price : 25,
        image : "/pics/img-45.jpg",
    },
    {
        id : 46,
        name : "Electric Shaver",
        info : " is a razor with an electrically powered rotating or oscillating blade.",
        quantity : 1,
        price : 60,
        image : "/pics/img-46.jpg",
    },
    {
        id : 47,
        name : "electronic censer",
        info : "The electric censer is suitable for all kinds of commercial electric vehicle, easy to replace",
        quantity : 5,
        price : 55,
        image : "/pics/img-47.jpg",
    },
    {
        id : 48,
        name : "kettle",
        info : "A kettle, sometimes called a tea kettle or teakettle, is a type of pot specialized for boiling water",
        quantity : 12,
        price : 70,
        image : "/pics/img-48.jpg",
    },
    {
        id : 49,
        name : "Juicer Machines",
        info : "A juicer, also known as a juice extractor, is a tool used to extract juice from fruits, herbs, leafy greens and other types of vegetables in a process",
        quantity : 4,
        price : 100,
        image : "/pics/img-49.jpg",
    },
    {
        id : 50,
        name : "telephone",
        info : "A telephone converts sound, typically and most efficiently the human voice, into electronic signals that are transmitted via cables",
        quantity : 1,
        price : 30,
        image : "/pics/img-50.jpg",
    },
]
// info.html section
let imgShow = document.querySelector(".img-show");
let titleShow = document.querySelector(".title-show");
let textShow = document.querySelector(".text-show");
let quantityShow = document.querySelector(".quantity-show");
let priceShow = document.querySelector(".price-show");
// const trick = document.querySelector(".trick")
let id ;
if (window.localStorage.getItem("productID") === undefined ) {
    id = 0
}
else {
    id = window.localStorage.getItem("productID");
}

imgShow.src = allItems[id].image;
titleShow.textContent = allItems[id].name;
textShow.textContent = allItems[id].info;
quantityShow.textContent = `${allItems[id].quantity} left`;
priceShow.textContent =`${allItems[id].price}$`;